<?php
require_once '../../Queue.php';
require_once '../../Person.php';


/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-24 at 06:35:14.
 */
class QueueTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Queue
     */
    protected $queue;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->queue = new Queue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Queue::add
     */
    public function testAdd() {

        $personObj = new Person();
        $personObj->setForename("Marco");
        $personObj->setForename("Peter");
        $personObj->setForename(24);
         
        $result = $this->queue->add($personObj);
        
        $this->assertEquals(true, $result);
    }

    /**
     * @covers Queue::remove
     */
    public function testRemove() {

        $personObj = new Person();
        $personObj->setForename("Marco");
        $personObj->setLastname("Peter");
        $personObj->setAge(24);
        
        $result = $this->queue->add($personObj);
        
        $personResultObj = $this->queue->remove();
                
        $this->assertEquals("Marco", $personResultObj->getForename());
        $this->assertEquals("Peter", $personResultObj->getLastname());
        $this->assertEquals(24, $personResultObj->getAge());
    }

    /**
     * @covers Queue::length
     */
    public function testLength() {
        

        $personObj = new Person();
        $personObj->setForename("Marco");
        $personObj->setLastname("Peter");
        $personObj->setAge(24);
         
        
        $result = $this->queue->add($personObj);
        
        $this->assertEquals(1, $this->queue->length());
    }

}
