<?php
require_once '../../Person.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-21 at 17:33:13.
 */
class PersonTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Person
     */
    protected $person;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->person = new Person;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Person::getForename
     */
    public function testForename() {
        $this->person = new Person;
        $this->person->setForename("Marco");
        $this->assertEquals('Marco', $this->person->getForename());
        
        $this->person = new Person;
        $this->person->setForename("1234123");
        $this->assertEquals('', $this->person->getForename());
        
        $this->person = new Person;
        $this->person->setForename("£!?");
        $this->assertEquals('', $this->person->getForename());
        
        $this->person = new Person;
        $this->person->setForename("");
        $this->assertEquals('', $this->person->getForename());
        
        $this->person = new Person;
        $this->person->setForename("SELECT * FROM");
        $this->assertEquals('', $this->person->getForename());
    }

    /**
     * @covers Person::getLastname
     */
    public function testLastname() {
        $this->person = new Person;
        $this->person->setLastname("Peter");
        $this->assertEquals('Peter', $this->person->getLastname());
        
        $this->person = new Person;
        $this->person->setLastname("1234123");
        $this->assertEquals('', $this->person->getLastname());
        
        $this->person = new Person;
        $this->person->setLastname("£!?");
        $this->assertEquals('', $this->person->getLastname());
        
        $this->person = new Person;
        $this->person->setLastname("");
        $this->assertEquals('', $this->person->getLastname());
        
        $this->person = new Person;
        $this->person->setLastname("SELECT * FROM");
        $this->assertEquals('', $this->person->getLastname());
    }

    /**
     * @covers Person::getAge
     */
    public function testAge() {
        $this->person = new Person;
        $this->person->setAge(24);
        $this->assertEquals(24, $this->person->getAge());
        
        $this->person = new Person;
        $this->person->setAge(7);
        $this->assertEquals('', $this->person->getAge());
        
        $this->person = new Person;
        $this->person->setAge(99999);
        $this->assertEquals('', $this->person->getAge());
        
        $this->person = new Person;
        $this->person->setAge(99);
        $this->assertEquals(99, $this->person->getAge());
    }

}
