<?php
require_once '../../Queue.php';
/* FALSCH! Beim Komponententest darf keine Instanz einer anderen Klasse übergeben werden.
//require_once '../Person.php';
 */

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-24 at 06:35:14.
 */
class QueueTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Queue
     */
    protected $queue;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->queue = new Queue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Queue::add
     */
    public function testAdd() {
        
        $mock = $this->getMockBuilder('Person')->setMethods(["setForename", "setLastname", "setAge","getForename", "getLastname", "getAge"])->getMock();
        
        $mock->method('setForename')
            ->will($this->returnValue("Marco"));
        $mock->method('getForename')
            ->will($this->returnValue($mock->setForename()));
        
        $mock->method('setLastname')
             ->will($this->returnValue("Peter"));
        $mock->method('getLastname')
            ->will($this->returnValue($mock->setLastname()));
        
        $mock->method('setAge')
             ->will($this->returnValue(24));
        $mock->method('getAge')
            ->will($this->returnValue($mock->setAge()));
        
        /*
         * FALSCH! Beim Komponententest darf keine Instanz einer anderen Klasse übergeben werden.
         * 
        $personObj = new Person();
        $personObj->setForename("Marco");
        $personObj->setForename("Peter");
        $personObj->setForename(24);
         */

        $result = $this->queue->add($mock);
        
        $this->assertEquals(true, $result);
    }

    /**
     * @covers Queue::remove
     */
    public function testRemove() {
        
        $mock = $this->getMockBuilder('Person')->setMethods(["setForename", "setLastname", "setAge","getForename", "getLastname", "getAge"])->getMock();
        
        $mock->method('setForename')
            ->will($this->returnValue("Marco"));
        $mock->method('getForename')
            ->will($this->returnValue($mock->setForename()));
        
        $mock->method('setLastname')
             ->will($this->returnValue("Peter"));
        $mock->method('getLastname')
            ->will($this->returnValue($mock->setLastname()));
        
        $mock->method('setAge')
             ->will($this->returnValue(24));
        $mock->method('getAge')
            ->will($this->returnValue($mock->setAge()));
        
        /*
         * FALSCH! Beim Komponententest darf keine Instanz einer anderen Klasse übergeben werden.
         * 
        $personObj = new Person();
        $personObj->setForename("Marco");
        $personObj->setLastname("Peter");
        $personObj->setAge(24);
        */
       
        $result = $this->queue->add($mock);
        
        $personResultObj = $this->queue->remove();
                
        $this->assertEquals("Marco", $personResultObj->getForename());
        $this->assertEquals("Peter", $personResultObj->getLastname());
        $this->assertEquals(24, $personResultObj->getAge());
    }

    /**
     * @covers Queue::length
     */
    public function testLength() {
        
        $mock = $this->getMockBuilder('Person')->setMethods(["setForename", "setLastname", "setAge","getForename", "getLastname", "getAge"])->getMock();

        $mock->method('setForename')
            ->will($this->returnValue("Marco"));
        $mock->method('getForename')
            ->will($this->returnValue($mock->setForename()));

        $mock->method('setLastname')
             ->will($this->returnValue("Peter"));
        $mock->method('getLastname')
            ->will($this->returnValue($mock->setLastname()));

        $mock->method('setAge')
             ->will($this->returnValue(24));
        $mock->method('getAge')
            ->will($this->returnValue($mock->setAge()));
        
        /*
         * FALSCH! Beim Komponententest darf keine Instanz einer anderen Klasse übergeben werden.
         * 
        $personObj = new Person();
        $personObj->setForename("Marco");
        $personObj->setLastname("Peter");
        $personObj->setAge(24);
         */
        
        $result = $this->queue->add($mock);
        
        $this->assertEquals(1, $this->queue->length());
    }

}
